### ISSUE TITLE
Typescript issue with .isAfter()

### ISSUE THREAD

**Issue by Jujunol** [ctavan/express-validator#345]
The typescript definition file shows that `.isAfter()` takes a `Date` as an argument but it seems that it really wants a string. After passing it a date using the following:
```
req.assert('start_date', "Please select a valid start date").optional().isDate().isAfter(unixToDate(minTimestamp));
```
I get the following error: 
```
TypeError: This library (validator.js) validates strings only
    at assertString (*/node_modules/express-validator/node_modules/validator/lib/util/assertString.js:9:11)
    at toDate (*/node_modules/express-validator/node_modules/validator/lib/toDate.js:15:30)
    at Object.isAfter (*/node_modules/express-validator/node_modules/validator/lib/isAfter.js:22:41)
    at Object.validator.(anonymous function) [as isAfter] (*/node_modules/express-validator/lib/express_validator.js:13:15)
    at ValidatorChain.isAfter (*/node_modules/express-validator/lib/express_validator.js:469:41)
```

**Comment by gustavohenke** [comment]
Hmm, yes, you're right. validator itself is not very descriptive on what it wants in the `isAfter`/`isBefore` arguments...
