### ISSUE TITLE
TypeError: next is not a function

### ISSUE THREAD

**Issue by chelsh** [ctavan/express-validator#360]
~~~
9|app      | TypeError: next is not a function
9|app      |     at Object.<anonymous> (/home/app/backend/node_modules/express-validator/lib/express_validator.js:462:5)
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:242:19
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25
9|app      |     at /home/app/backend/node_modules/express-load/lib/express-load.js:263:7
9|app      |     at iterate (/home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:131:13)
9|app      |     at /home/app/backend/node_modules/express-load/node_modules/async/lib/async.js:142:25

~~~

**Comment by chelsh** [comment]
express version is 4.14.0

**Comment by gustavohenke** [comment]
Can you create a reproducible example of your problem?

**Comment by gustavohenke** [comment]
Closing due to inactivity.
