### ISSUE TITLE
Unexpected token ... issue

### ISSUE THREAD

**Issue by sergivb01** [ctavan/express-validator#391]
I cloned this project (https://github.com/bradtraversy/loginapp) and after running `npm install` and after that `npm start` I am getting the following issue:

```
C:\Users\User\Desktop\loginapp\node_modules\express-validator\lib\express_validator.js:125
        chain[name] = (...options) => {
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\User\Desktop\loginapp\node_modules\express-validator\index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I am using the **latest** version.

**Comment by gustavohenke** [comment]
express-validator v4.0.0 depends on Node.js 6+.

I suppose that making this explicit in the README would have been a good idea 🤔
