### ISSUE TITLE
ERR! Invalid name: "@types/express" on npm install

### ISSUE THREAD

**Issue by carriedg** [ctavan/express-validator#416]
I'm getting the following error when trying to install express-validator:

```
$ npm install express-validator --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-validator" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@types/express"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cgibson\Desktop\customerapp\npm-debug.log


Info from npm debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express-validator' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express-validator
8 silly fetchNamedPackageData express-validator
9 silly mapToRegistry name express-validator
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express-validator',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express-validator',
12 silly mapToRegistry   name: 'express-validator',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express-validator
14 verbose request uri https://registry.npmjs.org/express-validator
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:50:22 PM
17 verbose request id 7df56aab6cd10ddd
18 verbose etag W/"59ba26bb-20858"
19 verbose lastModified Thu, 14 Sep 2017 06:50:35 GMT
20 http request GET https://registry.npmjs.org/express-validator
21 http 304 https://registry.npmjs.org/express-validator
22 verbose headers { date: 'Thu, 14 Sep 2017 23:50:21 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"59ba26bb-20858"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-bur17539-BUR',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1505433022.874377,VS0,VE30',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 14 Sep 2017 23:50:21 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"59ba26bb-20858"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-bur17539-BUR',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1505433022.874377,VS0,VE30',
23 silly get     vary: 'Accept-Encoding, Accept' } ]
24 verbose etag https://registry.npmjs.org/express-validator from cache
25 verbose get saving express-validator to C:\Users\cgibson\AppData\Roaming\npm-cache\registry.npmjs.org\express-validator\.cache.json
26 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule express-validator@4.1.1 checking installable status
40 silly cache add args [ 'express-validator', null ]
41 verbose cache add spec express-validator
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'express-validator',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'express-validator',
42 silly cache add   name: 'express-validator',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed express-validator@latest
44 verbose addNamed "latest" is being treated as a dist-tag for express-validator
45 info addNameTag [ 'express-validator', 'latest' ]
46 silly mapToRegistry name express-validator
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'express-validator',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'express-validator',
49 silly mapToRegistry   name: 'express-validator',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/express-validator
51 verbose addNameTag registry:https://registry.npmjs.org/express-validator not in flight; fetching
52 verbose get https://registry.npmjs.org/express-validator not expired, no request
53 silly addNameTag next cb for express-validator with tag latest
54 silly addNamed express-validator@4.1.1
55 verbose addNamed "4.1.1" is a plain semver version for express-validator
56 silly cache afterAdd express-validator@4.1.1
57 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\express-validator\4.1.1\package\package.json not in flight; writing
58 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
59 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\express-validator\4.1.1\package\package.json written
60 silly fetchNamedPackageData @types/express
61 silly mapToRegistry name @types/express
62 silly mapToRegistry scope (from package name) @types
63 verbose mapToRegistry no registry URL found in name for scope @types
64 silly mapToRegistry using default registry
65 silly mapToRegistry registry https://registry.npmjs.org/
66 silly mapToRegistry data Result {
66 silly mapToRegistry   raw: '@types/express',
66 silly mapToRegistry   scope: '@types',
66 silly mapToRegistry   escapedName: '@types%2fexpress',
66 silly mapToRegistry   name: '@types/express',
66 silly mapToRegistry   rawSpec: '',
66 silly mapToRegistry   spec: 'latest',
66 silly mapToRegistry   type: 'tag' }
67 silly mapToRegistry uri https://registry.npmjs.org/@types%2fexpress
68 silly fetchNamedPackageData lodash
69 silly mapToRegistry name lodash
70 silly mapToRegistry using default registry
71 silly mapToRegistry registry https://registry.npmjs.org/
72 silly mapToRegistry data Result {
72 silly mapToRegistry   raw: 'lodash',
72 silly mapToRegistry   scope: null,
72 silly mapToRegistry   escapedName: 'lodash',
72 silly mapToRegistry   name: 'lodash',
72 silly mapToRegistry   rawSpec: '',
72 silly mapToRegistry   spec: 'latest',
72 silly mapToRegistry   type: 'tag' }
73 silly mapToRegistry uri https://registry.npmjs.org/lodash
74 silly fetchNamedPackageData validator
75 silly mapToRegistry name validator
76 silly mapToRegistry using default registry
77 silly mapToRegistry registry https://registry.npmjs.org/
78 silly mapToRegistry data Result {
78 silly mapToRegistry   raw: 'validator',
78 silly mapToRegistry   scope: null,
78 silly mapToRegistry   escapedName: 'validator',
78 silly mapToRegistry   name: 'validator',
78 silly mapToRegistry   rawSpec: '',
78 silly mapToRegistry   spec: 'latest',
78 silly mapToRegistry   type: 'tag' }
79 silly mapToRegistry uri https://registry.npmjs.org/validator
80 verbose request uri https://registry.npmjs.org/lodash
81 verbose request no auth needed
82 info attempt registry request try #1 at 4:50:22 PM
83 verbose etag W/"59bac919-29e52"
84 verbose lastModified Thu, 14 Sep 2017 18:23:21 GMT
85 http request GET https://registry.npmjs.org/lodash
86 verbose request uri https://registry.npmjs.org/@types%2fexpress
87 verbose request no auth needed
88 info attempt registry request try #1 at 4:50:22 PM
89 verbose etag W/"599c5a40-4e5f"
90 verbose lastModified Tue, 22 Aug 2017 16:22:24 GMT
91 http request GET https://registry.npmjs.org/@types%2fexpress
92 verbose request uri https://registry.npmjs.org/validator
93 verbose request no auth needed
94 info attempt registry request try #1 at 4:50:22 PM
95 verbose etag W/"59b649d4-40038"
96 verbose lastModified Mon, 11 Sep 2017 08:31:16 GMT
97 http request GET https://registry.npmjs.org/validator
98 http 304 https://registry.npmjs.org/lodash
99 verbose headers { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
99 verbose headers   via: '1.1 varnish',
99 verbose headers   'cache-control': 'max-age=300',
99 verbose headers   etag: 'W/"59bac919-29e52"',
99 verbose headers   age: '196',
99 verbose headers   connection: 'keep-alive',
99 verbose headers   'x-served-by': 'cache-bur17539-BUR',
99 verbose headers   'x-cache': 'HIT',
99 verbose headers   'x-cache-hits': '2',
99 verbose headers   'x-timer': 'S1505433022.042967,VS0,VE0',
99 verbose headers   vary: 'Accept-Encoding, Accept' }
100 silly get cb [ 304,
100 silly get   { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
100 silly get     via: '1.1 varnish',
100 silly get     'cache-control': 'max-age=300',
100 silly get     etag: 'W/"59bac919-29e52"',
100 silly get     age: '196',
100 silly get     connection: 'keep-alive',
100 silly get     'x-served-by': 'cache-bur17539-BUR',
100 silly get     'x-cache': 'HIT',
100 silly get     'x-cache-hits': '2',
100 silly get     'x-timer': 'S1505433022.042967,VS0,VE0',
100 silly get     vary: 'Accept-Encoding, Accept' } ]
101 verbose etag https://registry.npmjs.org/lodash from cache
102 verbose get saving lodash to C:\Users\cgibson\AppData\Roaming\npm-cache\registry.npmjs.org\lodash\.cache.json
103 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
104 http 304 https://registry.npmjs.org/validator
105 verbose headers { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
105 verbose headers   via: '1.1 varnish',
105 verbose headers   'cache-control': 'max-age=300',
105 verbose headers   etag: 'W/"59b649d4-40038"',
105 verbose headers   age: '3',
105 verbose headers   connection: 'keep-alive',
105 verbose headers   'x-served-by': 'cache-bur17539-BUR',
105 verbose headers   'x-cache': 'HIT',
105 verbose headers   'x-cache-hits': '1',
105 verbose headers   'x-timer': 'S1505433022.052436,VS0,VE0',
105 verbose headers   vary: 'Accept-Encoding, Accept' }
106 silly get cb [ 304,
106 silly get   { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
106 silly get     via: '1.1 varnish',
106 silly get     'cache-control': 'max-age=300',
106 silly get     etag: 'W/"59b649d4-40038"',
106 silly get     age: '3',
106 silly get     connection: 'keep-alive',
106 silly get     'x-served-by': 'cache-bur17539-BUR',
106 silly get     'x-cache': 'HIT',
106 silly get     'x-cache-hits': '1',
106 silly get     'x-timer': 'S1505433022.052436,VS0,VE0',
106 silly get     vary: 'Accept-Encoding, Accept' } ]
107 verbose etag https://registry.npmjs.org/validator from cache
108 verbose get saving validator to C:\Users\cgibson\AppData\Roaming\npm-cache\registry.npmjs.org\validator\.cache.json
109 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
110 silly resolveWithNewModule lodash@4.17.4 checking installable status
111 silly cache add args [ 'lodash@^4.16.0', null ]
112 verbose cache add spec lodash@^4.16.0
113 silly cache add parsed spec Result {
113 silly cache add   raw: 'lodash@^4.16.0',
113 silly cache add   scope: null,
113 silly cache add   escapedName: 'lodash',
113 silly cache add   name: 'lodash',
113 silly cache add   rawSpec: '^4.16.0',
113 silly cache add   spec: '>=4.16.0 <5.0.0',
113 silly cache add   type: 'range' }
114 silly addNamed lodash@>=4.16.0 <5.0.0
115 verbose addNamed ">=4.16.0 <5.0.0" is a valid semver range for lodash
116 silly addNameRange { name: 'lodash', range: '>=4.16.0 <5.0.0', hasData: false }
117 silly mapToRegistry name lodash
118 silly mapToRegistry using default registry
119 silly mapToRegistry registry https://registry.npmjs.org/
120 silly mapToRegistry data Result {
120 silly mapToRegistry   raw: 'lodash',
120 silly mapToRegistry   scope: null,
120 silly mapToRegistry   escapedName: 'lodash',
120 silly mapToRegistry   name: 'lodash',
120 silly mapToRegistry   rawSpec: '',
120 silly mapToRegistry   spec: 'latest',
120 silly mapToRegistry   type: 'tag' }
121 silly mapToRegistry uri https://registry.npmjs.org/lodash
122 verbose addNameRange registry:https://registry.npmjs.org/lodash not in flight; fetching
123 silly resolveWithNewModule validator@8.1.0 checking installable status
124 silly cache add args [ 'validator@~8.1.0', null ]
125 verbose cache add spec validator@~8.1.0
126 silly cache add parsed spec Result {
126 silly cache add   raw: 'validator@~8.1.0',
126 silly cache add   scope: null,
126 silly cache add   escapedName: 'validator',
126 silly cache add   name: 'validator',
126 silly cache add   rawSpec: '~8.1.0',
126 silly cache add   spec: '>=8.1.0 <8.2.0',
126 silly cache add   type: 'range' }
127 silly addNamed validator@>=8.1.0 <8.2.0
128 verbose addNamed ">=8.1.0 <8.2.0" is a valid semver range for validator
129 silly addNameRange { name: 'validator', range: '>=8.1.0 <8.2.0', hasData: false }
130 silly mapToRegistry name validator
131 silly mapToRegistry using default registry
132 silly mapToRegistry registry https://registry.npmjs.org/
133 silly mapToRegistry data Result {
133 silly mapToRegistry   raw: 'validator',
133 silly mapToRegistry   scope: null,
133 silly mapToRegistry   escapedName: 'validator',
133 silly mapToRegistry   name: 'validator',
133 silly mapToRegistry   rawSpec: '',
133 silly mapToRegistry   spec: 'latest',
133 silly mapToRegistry   type: 'tag' }
134 silly mapToRegistry uri https://registry.npmjs.org/validator
135 verbose addNameRange registry:https://registry.npmjs.org/validator not in flight; fetching
136 verbose get https://registry.npmjs.org/lodash not expired, no request
137 silly addNameRange number 2 { name: 'lodash', range: '>=4.16.0 <5.0.0', hasData: true }
138 silly addNameRange versions [ 'lodash',
138 silly addNameRange   [ '0.1.0',
138 silly addNameRange     '0.2.0',
138 silly addNameRange     '0.2.1',
138 silly addNameRange     '0.2.2',
138 silly addNameRange     '0.3.0',
138 silly addNameRange     '0.3.1',
138 silly addNameRange     '0.3.2',
138 silly addNameRange     '0.4.0',
138 silly addNameRange     '0.4.1',
138 silly addNameRange     '0.4.2',
138 silly addNameRange     '0.5.0-rc.1',
138 silly addNameRange     '0.5.0',
138 silly addNameRange     '0.5.1',
138 silly addNameRange     '0.5.2',
138 silly addNameRange     '0.6.0',
138 silly addNameRange     '0.6.1',
138 silly addNameRange     '0.7.0',
138 silly addNameRange     '0.8.0',
138 silly addNameRange     '0.8.1',
138 silly addNameRange     '0.8.2',
138 silly addNameRange     '0.9.0',
138 silly addNameRange     '0.9.1',
138 silly addNameRange     '0.9.2',
138 silly addNameRange     '0.10.0',
138 silly addNameRange     '1.0.0-rc.1',
138 silly addNameRange     '1.0.0-rc.2',
138 silly addNameRange     '1.0.0-rc.3',
138 silly addNameRange     '1.0.0',
138 silly addNameRange     '1.0.1',
138 silly addNameRange     '1.1.0',
138 silly addNameRange     '1.1.1',
138 silly addNameRange     '1.2.0',
138 silly addNameRange     '1.2.1',
138 silly addNameRange     '1.3.0',
138 silly addNameRange     '1.3.1',
138 silly addNameRange     '2.0.0',
138 silly addNameRange     '2.1.0',
138 silly addNameRange     '2.2.0',
138 silly addNameRange     '2.2.1',
138 silly addNameRange     '2.3.0',
138 silly addNameRange     '2.4.0',
138 silly addNameRange     '2.4.1',
138 silly addNameRange     '3.0.0',
138 silly addNameRange     '3.0.1',
138 silly addNameRange     '3.1.0',
138 silly addNameRange     '3.2.0',
138 silly addNameRange     '3.3.0',
138 silly addNameRange     '3.3.1',
138 silly addNameRange     '3.4.0',
138 silly addNameRange     '3.5.0',
138 silly addNameRange     '3.6.0',
138 silly addNameRange     '1.0.2',
138 silly addNameRange     '3.7.0',
138 silly addNameRange     '2.4.2',
138 silly addNameRange     '3.8.0',
138 silly addNameRange     '3.9.0',
138 silly addNameRange     '3.9.1',
138 silly addNameRange     '3.9.2',
138 silly addNameRange     '3.9.3',
138 silly addNameRange     '3.10.0',
138 silly addNameRange     '3.10.1',
138 silly addNameRange     '4.0.0',
138 silly addNameRange     '4.0.1',
138 silly addNameRange     '4.1.0',
138 silly addNameRange     '4.2.0',
138 silly addNameRange     '4.2.1',
138 silly addNameRange     '4.3.0',
138 silly addNameRange     '4.4.0',
138 silly addNameRange     '4.5.0',
138 silly addNameRange     '4.5.1',
138 silly addNameRange     '4.6.0',
138 silly addNameRange     '4.6.1',
138 silly addNameRange     '4.7.0',
138 silly addNameRange     '4.8.0',
138 silly addNameRange     '4.8.1',
138 silly addNameRange     '4.8.2',
138 silly addNameRange     '4.9.0',
138 silly addNameRange     '4.10.0',
138 silly addNameRange     '4.11.0',
138 silly addNameRange     '4.11.1',
138 silly addNameRange     '4.11.2',
138 silly addNameRange     '4.12.0',
138 silly addNameRange     '4.13.0',
138 silly addNameRange     '4.13.1',
138 silly addNameRange     '4.14.0',
138 silly addNameRange     '4.14.1',
138 silly addNameRange     '4.14.2',
138 silly addNameRange     '4.15.0',
138 silly addNameRange     '4.16.0',
138 silly addNameRange     '4.16.1',
138 silly addNameRange     '4.16.2',
138 silly addNameRange     '4.16.3',
138 silly addNameRange     '4.16.4',
138 silly addNameRange     '4.16.5',
138 silly addNameRange     '4.16.6',
138 silly addNameRange     '4.17.0',
138 silly addNameRange     '4.17.1',
138 silly addNameRange     '4.17.2',
138 silly addNameRange     '4.17.3',
138 silly addNameRange     '4.17.4' ] ]
139 silly addNamed lodash@4.17.4
140 verbose addNamed "4.17.4" is a plain semver version for lodash
141 verbose get https://registry.npmjs.org/validator not expired, no request
142 silly addNameRange number 2 { name: 'validator', range: '>=8.1.0 <8.2.0', hasData: true }
143 silly addNameRange versions [ 'validator',
143 silly addNameRange   [ '0.1.0',
143 silly addNameRange     '0.1.1',
143 silly addNameRange     '0.1.2',
143 silly addNameRange     '0.1.3',
143 silly addNameRange     '0.1.4',
143 silly addNameRange     '0.1.5',
143 silly addNameRange     '0.1.6',
143 silly addNameRange     '0.1.7',
143 silly addNameRange     '0.1.8',
143 silly addNameRange     '0.1.9',
143 silly addNameRange     '0.2.0',
143 silly addNameRange     '0.2.1',
143 silly addNameRange     '0.2.2',
143 silly addNameRange     '0.2.3',
143 silly addNameRange     '0.2.4',
143 silly addNameRange     '0.2.5',
143 silly addNameRange     '0.2.6',
143 silly addNameRange     '0.2.7',
143 silly addNameRange     '0.2.8',
143 silly addNameRange     '0.2.9',
143 silly addNameRange     '0.3.0',
143 silly addNameRange     '0.3.1',
143 silly addNameRange     '0.3.2',
143 silly addNameRange     '0.3.4',
143 silly addNameRange     '0.3.5',
143 silly addNameRange     '0.3.6',
143 silly addNameRange     '0.3.7',
143 silly addNameRange     '0.3.8',
143 silly addNameRange     '0.3.9',
143 silly addNameRange     '0.4.0',
143 silly addNameRange     '0.4.1',
143 silly addNameRange     '0.4.2',
143 silly addNameRange     '0.4.3',
143 silly addNameRange     '0.4.4',
143 silly addNameRange     '0.4.5',
143 silly addNameRange     '0.4.6',
143 silly addNameRange     '0.4.6-1',
143 silly addNameRange     '0.4.6-2',
143 silly addNameRange     '0.4.6-3',
143 silly addNameRange     '0.4.7',
143 silly addNameRange     '0.4.8',
143 silly addNameRange     '0.4.9',
143 silly addNameRange     '0.4.10',
143 silly addNameRange     '0.4.11',
143 silly addNameRange     '0.4.12',
143 silly addNameRange     '0.4.13',
143 silly addNameRange     '0.4.15',
143 silly addNameRange     '0.4.16',
143 silly addNameRange     '0.4.17',
143 silly addNameRange     '0.4.18',
143 silly addNameRange     '0.4.19',
143 silly addNameRange     '0.4.20',
143 silly addNameRange     '0.4.21',
143 silly addNameRange     '0.4.22',
143 silly addNameRange     '0.4.23',
143 silly addNameRange     '0.4.24',
143 silly addNameRange     '0.4.25',
143 silly addNameRange     '0.4.27',
143 silly addNameRange     '0.4.28',
143 silly addNameRange     '0.5.0',
143 silly addNameRange     '1.0.0',
143 silly addNameRange     '1.1.0',
143 silly addNameRange     '1.1.1',
143 silly addNameRange     '1.1.2',
143 silly addNameRange     '1.1.3',
143 silly addNameRange     '1.2.0',
143 silly addNameRange     '1.2.1',
143 silly addNameRange     '1.2.2',
143 silly addNameRange     '1.3.0',
143 silly addNameRange     '1.4.0',
143 silly addNameRange     '1.5.0',
143 silly addNameRange     '1.5.1',
143 silly addNameRange     '2.0.0',
143 silly addNameRange     '2.1.0',
143 silly addNameRange     '3.0.0',
143 silly addNameRange     '3.1.0',
143 silly addNameRange     '3.2.0',
143 silly addNameRange     '3.2.1',
143 silly addNameRange     '3.3.0',
143 silly addNameRange     '3.4.0',
143 silly addNameRange     '3.5.0',
143 silly addNameRange     '3.5.1',
143 silly addNameRange     '3.6.0',
143 silly addNameRange     '3.7.0',
143 silly addNameRange     '3.8.0',
143 silly addNameRange     '3.9.0',
143 silly addNameRange     '3.10.0',
143 silly addNameRange     '3.11.0',
143 silly addNameRange     '3.11.1',
143 silly addNameRange     '3.11.2',
143 silly addNameRange     '3.12.0',
143 silly addNameRange     '3.13.0',
143 silly addNameRange     '3.14.0',
143 silly addNameRange     '3.14.1',
143 silly addNameRange     '3.15.0',
143 silly addNameRange     '3.16.0',
143 silly addNameRange     '3.16.1',
143 silly addNameRange     '3.17.0',
143 silly addNameRange     '3.17.1',
143 silly addNameRange     '3.17.2',
143 silly addNameRange     ... 73 more items ] ]
144 silly addNamed validator@8.1.0
145 verbose addNamed "8.1.0" is a plain semver version for validator
146 silly cache afterAdd lodash@4.17.4
147 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\lodash\4.17.4\package\package.json not in flight; writing
148 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
149 silly cache afterAdd validator@8.1.0
150 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\validator\8.1.0\package\package.json not in flight; writing
151 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
152 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\validator\8.1.0\package\package.json written
153 verbose afterAdd C:\Users\cgibson\AppData\Roaming\npm-cache\lodash\4.17.4\package\package.json written
154 http 304 https://registry.npmjs.org/@types%2fexpress
155 verbose headers { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
155 verbose headers   via: '1.1 varnish',
155 verbose headers   'cache-control': 'max-age=0',
155 verbose headers   etag: 'W/"599c5a40-4e5f"',
155 verbose headers   age: '0',
155 verbose headers   connection: 'keep-alive',
155 verbose headers   'x-served-by': 'cache-bur17542-BUR',
155 verbose headers   'x-cache': 'MISS',
155 verbose headers   'x-cache-hits': '0',
155 verbose headers   'x-timer': 'S1505433022.056317,VS0,VE163',
155 verbose headers   vary: 'Accept-Encoding' }
156 silly get cb [ 304,
156 silly get   { date: 'Thu, 14 Sep 2017 23:50:22 GMT',
156 silly get     via: '1.1 varnish',
156 silly get     'cache-control': 'max-age=0',
156 silly get     etag: 'W/"599c5a40-4e5f"',
156 silly get     age: '0',
156 silly get     connection: 'keep-alive',
156 silly get     'x-served-by': 'cache-bur17542-BUR',
156 silly get     'x-cache': 'MISS',
156 silly get     'x-cache-hits': '0',
156 silly get     'x-timer': 'S1505433022.056317,VS0,VE163',
156 silly get     vary: 'Accept-Encoding' } ]
157 verbose etag https://registry.npmjs.org/@types%2fexpress from cache
158 verbose get saving @types/express to C:\Users\cgibson\AppData\Roaming\npm-cache\registry.npmjs.org\_40types_252fexpress\.cache.json
159 verbose correctMkdir C:\Users\cgibson\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
160 silly resolveWithNewModule @types/express@4.0.37 checking installable status
161 silly cache add args [ '@types/express@~4.0.34', null ]
162 verbose cache add spec @types/express@~4.0.34
163 silly cache add parsed spec Result {
163 silly cache add   raw: '@types/express@~4.0.34',
163 silly cache add   scope: '@types',
163 silly cache add   escapedName: '@types%2fexpress',
163 silly cache add   name: '@types/express',
163 silly cache add   rawSpec: '~4.0.34',
163 silly cache add   spec: '>=4.0.34 <4.1.0',
163 silly cache add   type: 'range' }
164 silly addNamed @types/express@>=4.0.34 <4.1.0
165 verbose addNamed ">=4.0.34 <4.1.0" is a valid semver range for @types/express
166 silly addNameRange { name: '@types/express',
166 silly addNameRange   range: '>=4.0.34 <4.1.0',
166 silly addNameRange   hasData: false }
167 silly mapToRegistry name @types/express
168 silly mapToRegistry scope (from package name) @types
169 verbose mapToRegistry no registry URL found in name for scope @types
170 silly mapToRegistry using default registry
171 silly mapToRegistry registry https://registry.npmjs.org/
172 silly mapToRegistry data Result {
172 silly mapToRegistry   raw: '@types/express',
172 silly mapToRegistry   scope: '@types',
172 silly mapToRegistry   escapedName: '@types%2fexpress',
172 silly mapToRegistry   name: '@types/express',
172 silly mapToRegistry   rawSpec: '',
172 silly mapToRegistry   spec: 'latest',
172 silly mapToRegistry   type: 'tag' }
173 silly mapToRegistry uri https://registry.npmjs.org/@types%2fexpress
174 verbose addNameRange registry:https://registry.npmjs.org/@types%2fexpress not in flight; fetching
175 verbose get https://registry.npmjs.org/@types%2fexpress not expired, no request
176 silly addNameRange number 2 { name: '@types/express',
176 silly addNameRange   range: '>=4.0.34 <4.1.0',
176 silly addNameRange   hasData: true }
177 silly addNameRange versions [ '@types/express',
177 silly addNameRange   [ '4.0.16-alpha',
177 silly addNameRange     '4.0.17-alpha',
177 silly addNameRange     '4.0.22-alpha',
177 silly addNameRange     '4.0.23-alpha',
177 silly addNameRange     '4.0.24-alpha',
177 silly addNameRange     '4.0.25-alpha',
177 silly addNameRange     '4.0.26-alpha',
177 silly addNameRange     '4.0.27-alpha',
177 silly addNameRange     '4.0.28-alpha',
177 silly addNameRange     '4.0.29',
177 silly addNameRange     '4.0.30',
177 silly addNameRange     '4.0.31',
177 silly addNameRange     '4.0.32',
177 silly addNameRange     '4.0.33',
177 silly addNameRange     '4.0.34',
177 silly addNameRange     '4.0.35',
177 silly addNameRange     '4.0.36',
177 silly addNameRange     '4.0.37' ] ]
178 silly addNamed @types/express@4.0.37
179 verbose addNamed "4.0.37" is a plain semver version for @types/express
180 silly rollbackFailedOptional Starting
181 silly rollbackFailedOptional Finishing
182 silly runTopLevelLifecycles Finishing
183 silly install printInstalled
184 verbose stack Error: Invalid name: "@types/express"
184 verbose stack     at ensureValidName (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:302:15)
184 verbose stack     at Object.fixNameField (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:206:5)
184 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:38
184 verbose stack     at Array.forEach (native)
184 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:28:15)
184 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
184 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
184 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
184 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
184 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
185 verbose cwd C:\Users\cgibson\Desktop\customerapp
186 error Windows_NT 6.1.7601
187 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-validator"
188 error node v6.11.3
189 error npm  v3.10.10
190 error Invalid name: "@types/express"
191 error If you need help, you may report this error at:
191 error     <https://github.com/npm/npm/issues>
192 verbose exit [ 1, true ]
```

**Comment by gustavohenke** [comment]
A simple search for "npm invalid name" led to me *lots* of results you might be interested in.
The best one seems to be this one: npm/npm#13986

The rule of thumb to fix this problem is to clear caches and reinstall latest npm version.
It's not a problem related to express-validator.

**Comment by carriedg** [comment]
I had actually already done a google search and already tried this. I guess I should have mentioned that. In the meantime I was able to install the form-validator module so I'll just use that.

Thx.

**Comment by danivijay** [comment]
Similar error occurred for me too. Sounds like this is not with npm but with express-validator itself. Already tried recommended solution of @gustavohenke. As @carriedg said, still not installing.

Link: ('types/express' is not in the npm registry.)[https://github.com/ctavan/express-validator/issues/488]

**Comment by danivijay** [comment]
Updating npm solved issue of mine, finally. It was 'chocolatey' which loaded an old version of npm. Check npm version with -v and location with 'where.exe'.
