### ISSUE TITLE
Cannot find module `express-validator/check`

### ISSUE THREAD

**Issue by vasiliy0s** [ctavan/express-validator#421]
I cant use 'check' chain as [you described](https://github.com/ctavan/express-validator#usage) in my project.

In my Node.js app (withing TypeScript) as saw logs when tryed to use:
```js
import { check } from 'express-validator/check';
// ...
```

`require` syntax does not help me with the same error.

I see next logs:
```log
backend_1  | @mfc-repub | 2017-09-19 07:29:30: TSError: ⨯ Unable to compile TypeScript
backend_1  | @mfc-repub | src/controllers/MenuItems.ts (3,41): Cannot find module 'express-validator/check'. (2307)
backend_1  | @mfc-repub |     at getOutput (/home/node/app/node_modules/ts-node/src/index.ts:307:15)
backend_1  | @mfc-repub |     at /home/node/app/node_modules/ts-node/src/index.ts:336:16
backend_1  | @mfc-repub |     at Object.compile (/home/node/app/node_modules/ts-node/src/index.ts:498:11)
backend_1  | @mfc-repub |     at Module.m._compile (/home/node/app/node_modules/ts-node/src/index.ts:392:43)
backend_1  | @mfc-repub |     at Module._extensions..js (module.js:635:10)
backend_1  | @mfc-repub |     at Object.require.extensions.(anonymous function) [as .ts] (/home/node/app/node_modules/ts-node/src/index.ts:395:12)
backend_1  | @mfc-repub |     at Module.load (module.js:545:32)
backend_1  | @mfc-repub |     at tryModuleLoad (module.js:508:12)
backend_1  | @mfc-repub |     at Function.Module._load (module.js:500:3)
backend_1  | @mfc-repub |     at Function.Module._load (/home/node/app/node_modules/tsconfig-paths/lib/register.js:24:35)
backend_1  | @mfc-repub |     at Module.require (module.js:568:17)
backend_1  | @mfc-repub |     at require (internal/module.js:11:18)
backend_1  | @mfc-repub |     at Object.<anonymous> (/home/node/app/src/route.ts:5:1)
backend_1  | @mfc-repub |     at Module._compile (module.js:624:30)
backend_1  | @mfc-repub |     at Module.m._compile (/home/node/app/node_modules/ts-node/src/index.ts:392:23)
backend_1  | @mfc-repub |     at Module._extensions..js (module.js:635:10)
backend_1  | @mfc-repub |     at Object.require.extensions.(anonymous function) [as .ts] (/home/node/app/node_modules/ts-node/src/index.ts:395:12)
backend_1  | @mfc-repub |     at Module.load (module.js:545:32)
backend_1  | @mfc-repub |     at tryModuleLoad (module.js:508:12)
backend_1  | @mfc-repub |     at Function.Module._load (module.js:500:3)
backend_1  | @mfc-repub |     at Function.Module._load (/home/node/app/node_modules/tsconfig-paths/lib/register.js:24:35)
backend_1  | @mfc-repub |     at Module.require (module.js:568:17)
backend_1  | [rundev] App @mfc-republic/backend restarted
```

Actually this package has no `check` or `fitler` directories for import:
```sh
vasiliy0s@nhn-cooking:~/projects/mfc-republic$ ll backend/node_modules/express-validator
total 104
drwxrwxr-x   6 vasiliy0s vasiliy0s  4096 Sep 19 10:25 ./
drwxrwxr-x 259 vasiliy0s vasiliy0s 12288 Sep 19 10:25 ../
drwxrwxr-x   3 vasiliy0s vasiliy0s  4096 Sep 19 10:25 build/
-rw-rw-r--   1 vasiliy0s vasiliy0s   360 Jun  9 15:51 builtins.js
-rw-rw-r--   1 vasiliy0s vasiliy0s  1489 Apr 22 02:05 CONTRIBUTING.md
-rw-rw-r--   1 vasiliy0s vasiliy0s  1219 Jul  9 04:57 .eslintrc
-rw-rw-r--   1 vasiliy0s vasiliy0s 17829 Jul  9 05:01 index.d.ts
-rw-rw-r--   1 vasiliy0s vasiliy0s    56 Jun  9 13:55 index.js
drwxrwxr-x   2 vasiliy0s vasiliy0s  4096 Sep 19 10:25 lib/
-rw-rw-r--   1 vasiliy0s vasiliy0s  1100 Apr 22 02:05 LICENSE
drwxrwxr-x   3 vasiliy0s vasiliy0s  4096 Sep 19 10:25 node_modules/
-rw-rw-r--   1 vasiliy0s vasiliy0s    90 Apr 22 02:05 .npmignore
-rw-rw-r--   1 vasiliy0s vasiliy0s  3728 Sep 19 10:25 package.json
-rw-rw-r--   1 vasiliy0s vasiliy0s 17981 May  5 21:17 README.md
-rw-rw-r--   1 vasiliy0s vasiliy0s   483 Jul  9 04:57 tsconfig.json
drwxrwxr-x   2 vasiliy0s vasiliy0s  4096 Jun  9 13:50 .vscode/
```

My installation is:
```sh
vasiliy0s@nhn-cooking:~/projects/mfc-republic$ cat backend/package.json
{
  // ...
  "devDependencies": {
    "tslint": "5.6.0",
    "tslint-config-airbnb": "5.2.1",
    "tslint-microsoft-contrib": "5.0.1"
  },
  "dependencies": {
    "@types/bcrypt-nodejs": "0.0.30",
    "@types/body-parser": "1.16.4",
    "@types/compression": "0.0.33",
    "@types/connect-mongo": "0.0.33",
    "@types/cors": "2.8.1",
    "@types/dotenv": "4.0.0",
    "@types/jsonwebtoken": "7.2.3",
    "@types/mongoose": "4.7.20",
    "@types/morgan": "1.7.32",
    "@types/node": "8.0.22",
    "@types/passport": "0.3.3",
    "@types/passport-jwt": "2.0.24",
    "@types/passport-local": "1.0.30",
    "@types/validator": "6.2.3",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "1.17.2",
    "compression": "1.7.0",
    "connect-mongo": "1.3.2",
    "cors": "2.8.4",
    "dotenv": "4.0.0",
    "express": "4.15.4",
    "express-validator": "3.2.1",
    "jsonwebtoken": "7.4.3",
    "mongoose": "4.11.7",
    "mongoose-delete": "0.4.0",
    "mongoose-timestamp": "0.6.0",
    "morgan": "1.8.2",
    "passport": "0.4.0",
    "passport-jwt": "3.0.0",
    "passport-local": "1.0.0",
    "pm2": "2.6.1",
    "ts-node": "3.3.0",
    "tsconfig-paths": "2.2.0",
    "tslib": "1.7.1",
    "typescript": "2.4.2",
    "validator": "8.2.0"
  }
}
```

**Comment by vasiliy0s** [comment]
Closed because I used @3 version of package instead of @4. Sorry for impatience, guys!)

**Comment by gustavohenke** [comment]
You're welcome!
