### ISSUE TITLE
first demo is error: TypeError: check(...).trim is not a function

### ISSUE THREAD

**Issue by chua1989** [ctavan/express-validator#424]
code:
```
  check('username')
  // .isEmail().withMessage('must be an email')

  // Every sanitizer method in the validator lib is available as well!
  .trim()
  .normalizeEmail()

...
```

express-validator: 4.2.0

check('username') did not return trim function

**Comment by gustavohenke** [comment]
Hi @chua1989, are you still tracking this?

**Comment by dannypier** [comment]
@gustavohenke I'm seeing a similar issue. 

`var express = require('express');
var router = express.Router();
const { check, validationResult } = require('express-validator/check');
var userActions = require('./actions/user_actions')

router.post('/create', [
        check('email').trim().normalizeEmail(),
        check('password').exists(),
        check('confirm', 'passwords do not match')
            .exists()
            .custom((value, { req }) => value === req.body.password)
    ],
    function (req, res){
        const errors = validationResult(req);
        if (!errors.isEmpty()) {
            return res.status(422).json({ errors: errors.mapped() });
        }
        userActions.create(req, res)//, userHelper, familyHelper)
    })

module.exports = router;`

```
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="/stylesheets/style.css">
    </head>
    <body>
        <h1>This library (validator.js) validates strings only</h1>
        <h2></h2>
        <pre>TypeError: This library (validator.js) validates strings only
    at assertString (/path-api-core/node_modules/validator/lib/util/assertString.js:11:11)
    at ltrim (/path-api-core/node_modules/validator/lib/ltrim.js:15:30)
    at Object.trim [as sanitizer] (/path-api-core/node_modules/validator/lib/trim.js:19:51)
    at sanitizers.reduce (/path-api-core/node_modules/express-validator/check/select-fields.js:64:24)
    at Array.reduce (native)
    at field (/path-api-core/node_modules/express-validator/check/select-fields.js:62:30)
    at arrayMap (/path-api-core/node_modules/lodash/lodash.js:660:23)
    at Function.map (/path-api-core/node_modules/lodash/lodash.js:9571:14)
    at interceptor (/path-api-core/node_modules/lodash/lodash.js:16970:35)
    at thru (/path-api-core/node_modules/lodash/lodash.js:8812:14)</pre>
    </body>
</html>
```

**Comment by gustavohenke** [comment]
What's your express-validator version? v4.2.1 was released a few hours ago and it did include a fix for sanitization issues.

**Comment by dannypier** [comment]
Updated to 4.2.1 and no longer seeing the above error. trim doesn't seem to be working, however. That may be a different issue though. I'd consider this resolved from my end. Thanks @gustavohenke

**Comment by gustavohenke** [comment]
Nice to know,  @dannypier! Can you please open another issue, so I can look at it? Thanks!

**Comment by gustavohenke** [comment]
Closing since OP did not respond
