### ISSUE TITLE
checkHeader causes exception on validation failure

### ISSUE THREAD

**Issue by unusualbob** [ctavan/express-validator#45]
Instead of adding the error to req.validationErrors, a validation error in checkHeader will cause an exception.

```javascript
//name = 'abcd'
req.check('name').isNumeric();
console.log('errors', req.validationErrors());
```
results in a console output of:
`errors [ { param: 'name', msg: 'Invalid number', value: 'abcd' } ]`

While 
```javascript
req.checkHeader("referer").isNumeric();
console.log('errors', req.validationErrors());
```
results in a console output of:
```
ValidatorError: Invalid number
    at new exports.ValidatorError (/node_modules/express-validator/node_modules/validator/lib/validator.js:6:11)
    at Validator.error (/node_modules/express-validator/node_modules/validator/lib/validator.js:15:11)
    at Validator.(anonymous function) [as isNumeric] (/node_modules/express-validator/node_modules/validator/lib/validator.js:57:33)
```
The log statement is never called and instead that stacktrace appears. Clearly something is wrong with the checkHeader function.

**Comment by rustybailey** [comment]
This should be fixed: https://github.com/ctavan/express-validator#v023
