### ISSUE TITLE
Usage with ESM modules

### ISSUE THREAD

**Issue by DJviolin** [ctavan/express-validator#460]
I tried to import into an ESM module with this syntax:

```js
import { check, validationResult } from 'express-validator/check';
import { matchedData, sanitize } from 'express-validator/filter';
```
However I'm getting the following error:

```js
(node:29028) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: The requested module does not provide an export named 'check'
    at checkComplete (internal/loader/ModuleJob.js:86:27)
    at moduleJob.linked.then (internal/loader/ModuleJob.js:69:11)
    at <anonymous>
```

What is the correct usage with ESM modules turned on with `--experimental-modules` flag?

**Comment by DJviolin** [comment]
I tested with `@std/esm` package also. It only works of I turn `cjs: true`.

**Comment by DJviolin** [comment]
Solution from [Stackoverflow](https://stackoverflow.com/questions/46927589/express-validator-usage-with-esm-modules):

```js
import checkAPIs from 'express-validator/check';
import filterAPIs from 'express-validator/filter';

const { check, validationResult } = checkAPIs;
const { matchedData } = filterAPIs;
```
